UIWeb/Controllers/CategoriasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Dominio.Models;
using Microsoft.AspNetCore.Authorization;
using Repositorio.Context;

namespace UIWeb.Controllers
{
    public class CategoriasController : Controller
    {
        private readonly DatabaseContext _context;

        public CategoriasController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: Categorias
        [Authorize]
        public async Task<ActionResult> Index()
        {
            return View(await _context.Categorias.ToListAsync());
        }

        [Authorize]
        // GET: Categorias/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categorias = await _context.Categorias
                .FirstOrDefaultAsync(m => m.Id == id);
            if (categorias == null)
            {
                return NotFound();
            }

            return View(categorias);
        }

        [Authorize]
        // GET: Categorias/Create
        public ActionResult Create()
        {
            return View();
        }

        [Authorize]
        // POST: Categorias/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("Id,Descricao")] Categorias categorias)
        {
            if (ModelState.IsValid)
            {
                _context.Add(categorias);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(categorias);
        }

        [Authorize]
        // GET: Categorias/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categorias = await _context.Categorias.FindAsync(id);
            if (categorias == null)
            {
                return NotFound();
            }
            return View(categorias);
        }

        [Authorize]
        // POST: Categorias/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, [Bind("Id,Descricao")] Categorias categorias)
        {
            if (id != categorias.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categorias);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoriasExists(categorias.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(categorias);
        }

        [Authorize]
        // GET: Categorias/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categorias = await _context.Categorias
                .FirstOrDefaultAsync(m => m.Id == id);
            if (categorias == null)
            {
                return NotFound();
            }

            return View(categorias);
        }

        [Authorize]
        // POST: Categorias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var categorias = await _context.Categorias.FindAsync(id);
            _context.Categorias.Remove(categorias);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoriasExists(int id)
        {
            return _context.Categorias.Any(e => e.Id == id);
        }
    }
}

UIWeb/Controllers/ReceitasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Dominio.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Formatters;
using Repositorio.Context;

namespace UIWeb.Controllers
{
    public class ReceitasController : Controller
    {
        private readonly DatabaseContext _context;

        public ReceitasController(DatabaseContext context)
        {
            _context = context;
        }

        [Authorize]
        // GET: Receitas
        public async Task<ActionResult> Index()
        {
            var receitas = await _context.Receitas.Include(x => x.Categoria).ToListAsync();
            return View(receitas);

        }

        [Authorize]
        // GET: Receitas/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var receitas = await _context.Receitas.Include(x=>x.Categoria)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (receitas == null)
            {
                return NotFound();
            }

            return View(receitas);
        }

        [Authorize]
        // GET: Receitas/Create
        public ActionResult Create()
        {
            
            ViewBag.Categoria = ListaCategoria();
           
            return View();
        }

        [Authorize]
        // POST: Receitas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("Id,Titulo,Descricao,CategoriaId")] Receitas receitas)
        {
            ViewBag.Categoria = ListaCategoria();

            if (ModelState.IsValid)
            {
                _context.Add(receitas);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(receitas);
        }

        [Authorize]
        // GET: Receitas/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            ViewBag.Categoria = ListaCategoria();

            if (id == null)
            {
                return NotFound();
            }

            var receitas = await _context.Receitas.Include(x => x.Categoria)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (receitas == null)
            {
                return NotFound();
            }

            return View(receitas);
        }

        [Authorize]
        // POST: Receitas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, [Bind("Id,Titulo,Descricao,CategoriaId")] Receitas receitas)
        {
            ViewBag.Categoria = ListaCategoria();

            if (id != receitas.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(receitas);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReceitasExists(receitas.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View(receitas);
        }

        [Authorize]
        // GET: Receitas/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var receitas = await _context.Receitas
                .FirstOrDefaultAsync(m => m.Id == id);

            if (receitas == null)
            {
                return NotFound();
            }

            return View(receitas);
        }

        [Authorize]
        // POST: Receitas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var receitas = await _context.Receitas.FindAsync(id);
            _context.Receitas.Remove(receitas);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReceitasExists(int id)
        {
            return _context.Receitas.Any(e => e.Id == id);
        }

        public IEnumerable<SelectListItem> ListaCategoria()
        {
            IEnumerable<SelectListItem> listaCategoria =
                _context.Categorias.Select(s => new SelectListItem
                {
                    Text = s.Descricao,
                    Value = s.Id.ToString()
                });
            return listaCategoria;
        }
    }
}

UIWeb/Views/Shared/_CkeditorScriptsPartial.cshtml
<script src="~/lib/ckeditor/ckeditor.js"></script>
<script src="~/lib/ckeditor/lang/pt-br.js"></script>

UIWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UIWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
	            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img height="75" src="/img/logo.png"/></a>
	            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
	                    aria-expanded="false" aria-label="Toggle navigation">
		            <span class="navbar-toggler-icon"></span>
	            </button>

	            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
		            <ul class="navbar-nav flex-grow-1">
			            <li class="nav-item">
				            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
			            </li>
			            <li class="nav-item">
				            <a class="nav-link text-dark" asp-area="" asp-controller="Receitas" asp-action="Index">Receitas</a>
			            </li>
			            <li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Categorias" asp-action="Index">Categorias</a>
						</li>
		            </ul>
		            <ul class="nav navbar-nav navbar-right">
			            @if (User.Identity.IsAuthenticated)
			            {
						<li class="nav-item">
							<a class="nav-link text-dark">@("Bem vindo(a) " + User.Identity.Name + "!")</a>
						</li>
			            <li class="nav-item">
				            <a class="nav-link text-dark" asp-area="" asp-controller="Acesso" asp-action="Sair">Sair</a>
			            </li>
			            }
			            else
			            {
				            <li class="nav-item">
					            <a class="nav-link text-dark" asp-area="" asp-controller="Acesso" asp-action="Index">Acesso</a>
				            </li>	
			            }
		            </ul>
	            </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
	        &copy; 2021 - Recipes4Net 
	        @*<a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>